apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-02-06T21:51:18Z"
  labels:
    run: nginx
  name: nginx
  namespace: mynamespace
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always